[tool.poetry]
name = "sw-engineering-challenge"
version = "0.1.0"
description = ""
authors = ["anacrb <anacrb94@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
